accelerator: cpu
activation: ReLU
alias: null
batch_size: 256
drop_last_loader: false
dropout_prob_theta: 0.0
early_stop_patience_steps: 10
exclude_insample_y: false
futr_exog_list:
- temp
- precip
- snow
- snowdepth
- visibility
- windspeed
- week_sin
- week_cos
- day_sin
- day_cos
h: 1
hist_exog_list:
- rolling_mean_10
- rolling_std_10
- rolling_mean_50
- rolling_std_50
- rolling_max_10
inference_windows_batch_size: -1
input_size: 150
interpolation_mode: linear
learning_rate: 0.001
logger: !!python/object:pytorch_lightning.loggers.csv_logs.CSVLogger
  _experiment: !!python/object:pytorch_lightning.loggers.csv_logs.ExperimentWriter
    _fs: &id001 !!python/object/apply:fsspec.spec.make_instance
    - !!python/name:fsspec.implementations.local.LocalFileSystem ''
    - !!python/tuple []
    - {}
    hparams:
      accelerator: cpu
      activation: ReLU
      alias: null
      batch_size: 256
      drop_last_loader: false
      dropout_prob_theta: 0.0
      early_stop_patience_steps: 10
      exclude_insample_y: false
      futr_exog_list:
      - temp
      - precip
      - snow
      - snowdepth
      - visibility
      - windspeed
      - week_sin
      - week_cos
      - day_sin
      - day_cos
      h: 1
      hist_exog_list:
      - rolling_mean_10
      - rolling_std_10
      - rolling_mean_50
      - rolling_std_50
      - rolling_max_10
      inference_windows_batch_size: -1
      input_size: 150
      interpolation_mode: linear
      learning_rate: 0.001
      logger: !!python/object:pytorch_lightning.loggers.csv_logs.CSVLogger
        _experiment: null
        _flush_logs_every_n_steps: 100
        _fs: *id001
        _name: training_logs
        _prefix: ''
        _root_dir: /data/model
        _save_dir: /data/model
        _version: null
      loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: {}
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: {}
        _non_persistent_buffers_set: !!set {}
        _parameters:
          quantiles: !!python/object/apply:torch._utils._rebuild_parameter
          - !!python/object/apply:torch._utils._rebuild_tensor_v2
            - !!python/object/apply:torch.storage._load_from_bytes
              - !!binary |
                gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                Z2UKcQFYDwAAADE4NzY1MTIyNzQ5NzA1NnECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYDwAAADE4
                NzY1MTIyNzQ5NzA1NnEBYS4DAAAAAAAAAM3MzD0AAAA/ZmZmPw==
            - 0
            - !!python/tuple
              - 3
            - !!python/tuple
              - 1
            - false
            - !!python/object/apply:collections.OrderedDict
              - []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        horizon_weight: null
        is_distribution_output: false
        output_names:
        - -lo-80.0
        - -median
        - -hi-80.0
        outputsize_multiplier: 3
        training: true
      max_steps: 1000
      mlp_units:
      - &id002
        - 512
        - 512
      - *id002
      - *id002
      n_blocks:
      - 1
      - 1
      - 1
      n_freq_downsample:
      - 168
      - 24
      - 1
      n_pool_kernel_size:
      - 2
      - 2
      - 2
      num_lr_decays: 3
      num_workers_loader: 0
      pooling_mode: MaxPool1d
      random_seed: 1
      scaler_type: robust
      stack_types:
      - identity
      - identity
      - identity
      start_padding_enabled: false
      stat_exog_list: null
      step_size: 1
      val_check_steps: 100
      valid_batch_size: null
      valid_loss: null
      windows_batch_size: 1024
    log_dir: /data/model/training_logs/version_3
    metrics: []
    metrics_file_path: /data/model/training_logs/version_3/metrics.csv
    metrics_keys:
    - epoch
    - ptl/val_loss
    - step
    - train_loss_epoch
    - train_loss_step
    - valid_loss
  _flush_logs_every_n_steps: 100
  _fs: *id001
  _name: training_logs
  _prefix: ''
  _root_dir: /data/model
  _save_dir: /data/model
  _version: 3
loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDwAAADE4NzY1MTIyNzU5NzM5MnECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYDwAAADE4
          NzY1MTIyNzU5NzM5MnEBYS4DAAAAAAAAAM3MzD0AAAA/ZmZmPw==
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDwAAADE4NzY1MTIyNzYxMDYyNHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADE4
      NzY1MTIyNzYxMDYyNHEBYS4BAAAAAAAAAAAAgD8=
  - 0
  - !!python/tuple
    - 1
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  is_distribution_output: false
  output_names:
  - -lo-80.0
  - -median
  - -hi-80.0
  outputsize_multiplier: 3
  training: true
max_steps: 1000
mlp_units:
- &id003
  - 512
  - 512
- *id003
- *id003
n_blocks:
- 1
- 1
- 1
n_freq_downsample:
- 168
- 24
- 1
n_pool_kernel_size:
- 2
- 2
- 2
num_lr_decays: 3
num_workers_loader: 0
pooling_mode: MaxPool1d
random_seed: 1
scaler_type: robust
stack_types:
- identity
- identity
- identity
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
