FROM us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.2-4.py310:latest

WORKDIR /app

# Install uv for faster dependency resolution
RUN pip install uv

# Install python dependencies
COPY requirements.nhits.txt .
RUN uv pip install --system --no-cache -r requirements.nhits.txt

# Copy training code
COPY src/ src/

# Set entrypoint (optional)
# ENTRYPOINT ["python", "src/train_nhits.py"]
